.MODEL SMALL
.STACK 100H
.DATA
    ARR    DB 45H,12H,78H,33H,90H,05H,67H
    N      EQU 7
    MAXV   DB 0
    MINV   DB 0FFH
    MSG1   DB 0DH,0AH,'Maximum: $'
    MSG2   DB 0DH,0AH,'Minimum: $'
    HEXTAB DB '0123456789ABCDEF'
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX

    LEA SI,ARR
    MOV CX,N
    MOV AL,[SI]
    MOV MAXV,AL
    MOV MINV,AL
LOOP1:
    INC SI
    DEC CX
    JZ ENDLOOP1
    MOV AL,[SI]
    CMP AL,MAXV
    JBE CHKMIN
    MOV MAXV,AL
CHKMIN:
    CMP AL,MINV
    JAE LOOP1
    MOV MINV,AL
    JMP LOOP1
ENDLOOP1:

    MOV AH,09H
    LEA DX,MSG1
    INT 21H
    MOV AL,MAXV
    CALL PRINT_HEX_BYTE

    MOV AH,09H
    LEA DX,MSG2
    INT 21H
    MOV AL,MINV
    CALL PRINT_HEX_BYTE

    MOV AH,4CH
    INT 21H
MAIN ENDP

PRINT_HEX_BYTE PROC
    PUSH AX
    PUSH BX
    PUSH CX
    MOV CH,AL
    MOV CL,4
    SHR AL,CL
    AND AL,0FH
    LEA BX,HEXTAB
    XLAT
    MOV DL,AL
    MOV AH,02H
    INT 21H
    MOV AL,CH
    AND AL,0FH
    LEA BX,HEXTAB
    XLAT
    MOV DL,AL
    MOV AH,02H
    INT 21H
    POP CX
    POP BX
    POP AX
    RET
PRINT_HEX_BYTE ENDP
END MAIN
